---
- name: "Build docker images and push them to GCR"
  hosts: localhost
  gather_facts: false
  tasks:
  - name: "Get timestamp for docker tag"
    shell: "(date +%Y%m%d%H%M%S)"
    register: tag
  - name: Print tag
    debug:
      var: tag
  - name: Build container image
    community.general.docker_image:
      build:
        path: /agents
        platform: linux/amd64/v2
      name: gcr.io/{{ gcp_project }}/billionairs_agents:{{ tag.stdout}}
      source: build
  - name: Push image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/billionairs_agents:{{ tag.stdout}}
      repository: gcr.io/{{ gcp_project }}/billionairs_agents:{{ tag.stdout}}
      push: yes
      source: local
  - name: "Save docker tag"
    shell: echo {{ tag.stdout}} > .docker-tag
  - name: "Remove all unused containers"
    shell: docker system prune -a