apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
data:
  openai_key: c2stcHJvai1ZMmpsYlBxSTl5UXBDUW04RUo2RkVIdGhKd3pIQUQteVpQeWN1c3JVVF9SeUIzRGpuRkpPaElrTVRqQzJydkJvbW02SUl1WXQ5clQzQmxia0ZKN3V6clpFcUZTcEpQMHA3bU1rSzZoR2FPQU9URnhZQnAxcVFUR094WTd0WlZhVkhLeFlkSWJuWVRLWkE5V0YyTVZ6N011ZnA1Y0EK