apiVersion: v1
kind: Secret
metadata:
  name: openai-api-key
type: Opaque
data:
  OPENAI_API_KEY: YzJzdGNISnZhaTFaTW1wc1lsQnhTVGw1VVhCRFVXMDRSVW8yUmtWSWRHaEtkM3BJUVVRdGVWcFFlV04xYzNKVlZGOVNlVUl6UkdwdVJrcFBhRWxyVFZScVF6Snlka0p2YlcwMlNVbDFXWFE1Y2xRelFteGlhMFpLTjNWNmNscEZjVVpUY0VwUU1IQTNiVTFyU3pab1IyRlBRVTlVUm5oWlFuQXhjVkZVUjA5NFdUZDBXbFpoVmtoTGVGbGtTV0p1V1ZSTFdrRTVWMFl5VFZaNk4wMTFabkExWTBFSw==
    