version: '3.8'

services:
  api-service:
    build:
      context: ./src/api-service 
      dockerfile: Dockerfile    
    container_name: api-service
    ports:
      - "8001:8001"            
    environment:
      - PORT=8001               
      - OPENAI_API_KEY=${OPENAI_API_KEY}  
    networks:
      - my-network              

  frontend:
    build:
      context: ./src/frontend    
      dockerfile: Dockerfile     
    container_name: streamlit-container
    ports:
      - "8501:8501"             
    depends_on:
      - api-service             
    networks:
      - my-network               
    environment:
      - API_URL=http://api-service:8001

networks:
  my-network:
    driver: bridge
