version: '3.8'

services:
  api-service:
    build:
      context: ./src/api-service  
    ports:
      - "8001:8001"  # Maps the container port to the host
    networks:
      - my-network
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  
    volumes:
      - ./secrets:/run/secrets:ro 

  redis:
    image: "redis:alpine"  # Example of a Redis service
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
