name: CI CD for Billionaire App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_app:
    if: contains(github.event.head_commit.message, '/deploy-app')
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker Client for GCR
        run: gcloud auth configure-docker --quiet

      - name: Build deployment container
        run: |
          cd src/deployment
          docker build -t billionaire-app-deployment -f Dockerfile .

      # Run our deployment process inside the container
      - name: Run Deployment inside container
        run: |
          docker run --rm --name billionaire-app-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.ssh:/home/app/.ssh \
            -v ${{ github.workspace }}:/workspace \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e GCP_PROJECT=unified-canyon-436117-q9 \
            -e GCP_ZONE=us-east1-c \
            billionaire-app-deployment bash -c "
              cd /app/src/deployment && \
              # Build & push images
              ansible-playbook deploy-docker-images.yml -i inventory.yml && \
              # Update containers on VM
              ansible-playbook deploy-setup-containers.yml -i inventory.yml && \
              ansible-playbook deploy-setup-webserver.yml -i inventory.yml
            "
