name: CI CD for Billionaire App

on:
  push:
    branches: [ "milestone5" ]

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up gcloud auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      # Create secret files from GitHub secrets
      # Using printf instead of echo to avoid formatting issues
      - name: Prepare secrets
        run: |
          printf '%s' "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > deployment.json
          printf '%s' "${{ secrets.SSH_PRIVATE_KEY }}" > ssh-key-deployment
          chmod 600 ssh-key-deployment
          printf '%s' "${{ secrets.OPENAI_API_KEY }}" > openai_key.txt
          printf '%s' "${{ secrets.GCP_SERVICE_CREDENTIALS }}" > gcp-service.json

      # Debug step: Validate JSON and print directory listing
      - name: Debug secrets
        run: |
          echo "Checking deployment.json validity:"
          cat deployment.json || true
          # Validate JSON with jq
          jq . deployment.json
          
          echo "Listing files in workspace:"
          ls -al

      - name: Build deployment container
        run: |
          cd src/deployment
          docker build -t billionaire-app-deployment -f Dockerfile .

      - name: Run Deployment inside container
        run: |
          docker run --rm --name billionaire-app-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}:/workspace \
            -v ${{ github.workspace }}/deployment.json:/secrets/deployment.json:ro \
            -v ${{ github.workspace }}/ssh-key-deployment:/secrets/ssh-key-deployment:ro \
            -v ${{ github.workspace }}/openai_key.txt:/secrets/openai_key.txt:ro \
            -v ${{ github.workspace }}/gcp-service.json:/secrets/gcp-service.json:ro \
            -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e GCP_PROJECT=unified-canyon-436117-q9 \
            -e GCP_ZONE=us-east1-c \
            billionaire-app-deployment bash -c "
              cd /app/src/deployment && \
              echo 'Inside container, checking JSON:' && jq . /secrets/deployment.json && \
              ansible-playbook -vvv deploy-docker-images.yml -i inventory.yml && \
              ansible-playbook -vvv deploy-setup-containers.yml -i inventory.yml && \
              ansible-playbook -vvv deploy-setup-webserver.yml -i inventory.yml
            "
