name: CI CD for Billionaire App

on:
  push:
    branches: [ "milestone5" ]

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up gcloud auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Prepare secrets
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh-key-deployment
          chmod 600 ssh-key-deployment

      - name: Build deployment container
        run: |
          cd src/deployment
          docker build -t billionaire-app-deployment -f Dockerfile .

      - name: Run Deployment
        run: |
          docker run --rm --name billionaire-app-deployment \
            --entrypoint /bin/bash \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}:/workspace \
            -v ${{ github.workspace }}/src/deployment/deployment.json:/secrets/deployment.json:ro \
            -v ${{ github.workspace }}/ssh-key-deployment:/secrets/ssh-key-deployment:ro \
            -e ANSIBLE_HOST_KEY_CHECKING=False \
            -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e GCP_PROJECT=unified-canyon-436117-q9 \
            -e GCP_ZONE=us-east1-c \
            billionaire-app-deployment -c "
              # Authenticate inside the container
              gcloud auth activate-service-account --key-file=/secrets/deployment.json
              gcloud config set project \$GCP_PROJECT
              gcloud auth configure-docker gcr.io --quiet

              cd /workspace/src/deployment
              ansible-playbook deploy-docker-images.yml -i inventory.yml
              ansible-playbook deploy-setup-containers.yml -i inventory.yml
              ansible-playbook deploy-setup-webserver.yml -i inventory.yml
            "
