name: Multi-Container Integration Test

on:
  push:
    branches:
      - milestone4
  pull_request:
    branches:
      - milestone4

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build and run tests using docker-compose
      - name: Run tests with docker-compose
        run: |
          docker-compose -f docker/docker-compose.yml up --build --abort-on-container-exit

      # Clean up Docker resources
      - name: Clean up
        run: docker-compose -f docker/docker-compose.yml down
